language: cpp
dist: trusty
sudo: required
compiler:
  - gcc


# safelist
branches:
  only:
  - devel
#  - master

# download repo depedencies add the Player patch
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- git clone https://github.com/lsa-pucrs/Player.git
- git clone https://github.com/lsa-pucrs/Stage.git
# Player patches
- patch -p1 < patch/festival/festival.patch
- patch -p1 < patch/install/player_3.0.2_14.04.patch
- patch -p1 < patch/donnie/instalationSoundProxy.patch

# Install all of the dependencies:
install:
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y cmake
  - sudo apt-get install -y cmake-curses-gui
  - sudo apt-get install -y pkg-config
# install Player/Stage depedencies
  - sudo apt-get install -y libfltk1.1-dev 
  - sudo apt-get install -y freeglut3-dev 
  - sudo apt-get install -y libpng12-dev 
  - sudo apt-get install -y libltdl-dev 
   #libltdl7 
  - sudo apt-get install -y libdb5.1-stl
  - sudo apt-get install -y libgnomecanvasmm-2.6-dev
  - sudo apt-get install -y python-gnome2
  #sudo apt-get install -y libboost-all-dev  # overkill, the actually required libraries are boostthread, boostsignal, boostsystem
  - sudo apt-get install -y libboost-signals-dev libboost-system-dev libboost-thread-dev
  # old OpenCV for older Player drivers
  - sudo apt-get install -y libopencv-dev libopencv-core-dev libcv-dev libcvaux-dev libhighgui-dev
  - sudo apt-get install -y libasound2-dev
  - sudo apt-get install -y libgsl0-dev libxmu-dev
  #- sudo apt-get install -y python-dev swig
  # PostGIS for a Player driver
  - sudo apt-get install -y libpq-dev libpqxx-dev
# install Donnie's depedency
  - sudo apt-get install -y libsox-dev 
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y libreadline-dev
  #sudo apt-get install -y oracle-java8-installer
  - sudo apt-get install -y openjdk-7-jdk
  - sudo apt-get install -y libantlr3c-dev
  - apt-get install xterm


# Execute all of the commands which should make the build pass or fail
script:
# compile and install Player
  - cd Player
  - mkdir -p build # mkdir -p is safer !
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DDEBUG_LEVEL=NONE -BUILD_PYTHONC_BINDINGS:BOOL=OFF ..
  - make -j 8
  - sudo make install  
# compile and install Stage
  - cd ../Stage
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 8
  - make install
# compile and install Donnie
  - cd ..
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_DOCS=OFF -DBUILD_DOXYGEN=OFF -DBUILD_DOXYGEN_PDF=OFF -DBUILD_MANUAL=OFF -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
  - make -j 8
  - make install
