language: cpp
dist: trusty
sudo: required
compiler:
  - gcc


# safelist
branches:
  only:
  - devel
#  - master

# download repo depedencies add the Player patch
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
# install Player Stage deps
- sudo apt-get install -y pkg-config
# install Player/Stage depedencies
- sudo apt-get install -y libfltk1.1-dev freeglut3-dev libpng12-dev libltdl-dev libdb5.1-stl libgnomecanvasmm-2.6-dev python-gnome2
#sudo apt-get install -y libboost-all-dev  # overkill, the actually required libraries are boostthread, boostsignal, boostsystem
- sudo apt-get install -y libboost-signals-dev libboost-system-dev libboost-thread-dev libboost-locale-dev
# old OpenCV for older Player drivers
- sudo apt-get install -y libopencv-dev libopencv-core-dev libcv-dev libcvaux-dev libhighgui-dev
- sudo apt-get install -y libasound2-dev libgsl0-dev libxmu-dev libpq-dev libpqxx-dev
# install Player
- echo "Building Player"
- echo $(pwd)
- git clone https://github.com/lsa-pucrs/Player.git Player
- cd Player
- patch -p1 < patch/festival/festival.patch
- patch -p1 < patch/install/player_3.0.2_14.04.patch
- patch -p1 < patch/donnie/instalationSoundProxy.patch
- mkdir -p build # mkdir -p is safer !
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DDEBUG_LEVEL=NONE -BUILD_PYTHONC_BINDINGS:BOOL=OFF ..
- make -j 8
- sudo make install  
- cd ../..
# install Stage
- echo "Building Stage"
- echo $(pwd)
- git clone https://github.com/lsa-pucrs/Stage.git Stage
- cd Stage
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make -j 8
- sudo make install
- cd ../..

# install Donnie's depedency
install:
- sudo apt-get install -y libsox-dev 
- sudo apt-get install -y libcurl4-openssl-dev
- sudo apt-get install -y libreadline-dev
#sudo apt-get install -y oracle-java8-installer
- sudo apt-get install -y openjdk-7-jdk
- sudo apt-get install -y libantlr3c-dev
- sudo apt-get install -y xterm

# Execute all of the commands which should make the build pass or fail
script:
# compile and install Donnie
- echo "Building Donnie"
- echo $(pwd)
- export DONNIE_PATH=$(pwd)/install
- export CMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}:/usr/share/cmake-2.8/Modules/:/usr/share/cmake-2.8/Modules/Platform/:/usr/share/cmake-2.8/Modules/Compiler/:/usr/local/share/cmake/Modules:/usr/local/lib64/cmake/Stage/:/usr/lib/fltk/
- export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig/:/usr/share/pkgconfig/:${PKG_CONFIG_PATH}
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON -DBUILD_DOCS=OFF -DBUILD_DOXYGEN=OFF -DBUILD_DOXYGEN_PDF=OFF -DBUILD_MANUAL=OFF -DCMAKE_INSTALL_PREFIX=$(DONNIE_PATH) ..
- make -j 8
- sudo make install
- cd ..
