CXXFLAGS = `pkg-config --cflags playerc++ opencv` -g
CFLAGS = `pkg-config --cflags playerc opencv` -g
#LDLIBS = `pkg-config --libs playerc++` -std=c++0x -lboost_system
LDLIBS = `pkg-config --libs playerc++ opencv`
CC = g++
all: Blobfindertest
